services:
  factorio:
    image: factoriotools/factorio:2.0.76
    restart: always
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    env_file:
      - .env
    volumes:
      - ./data:/factorio
    environment:
      - DLC_SPACE_AGE=false
      - INSTANCE_NAME=yude.jp
