services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - ./config:/config
      - cache:/cache
      - /mnt/store4/dtv:/media-dtv
      - /mnt/prod/recorded:/media-recorded
    restart: always

volumes:
  cache:
