[server]
host-name=mt-daapd
use-ipv4=yes
use-ipv6=no

[wide-area]
enable-wide-area=no

[publish]
publish-aaaa-on-ipv4=no
publish-a-on-ipv6=no
publish-workstation=no
publish-domain=no
publish-dns-servers=no
publish-resolv-conf-dns-servers=no

[reflector]
enable-reflector=no
