web_root	/usr/share/mt-daapd
port		3689
admin_pw	admin
servername	nrt1-mt-daapd
mp3_dir		/music
db_dir		/var/cache/mt-daapd
runas		mt-daapd
password	
extensions	.mp3,.m4a,.m4p,.wav,.aiff
logfile		/var/log/mt-daapd.log
rescan_interval	300
compress	0
